const translations = {
  en: {
    brandName: 'Green & Inclusive Travel',
    tagline: 'Personalized Travel Decision Engine for sustainable and accessible travel in India',
    nav: {
      planTrip: 'Plan a Trip',
      explore: 'Explore',
      trips: 'Trips',
      forBusinesses: 'For Businesses',
      signIn: 'Sign in',
      profile: 'Profile',
      language: 'Language',
    },
    hero: {
      headlinePart1: 'Travel better.',
      headlinePart2: 'Travel lighter.',
      headlinePart3: 'Travel inclusively.',
      supporting: 'Plan trips around what matters to you — accessibility, budget, time, comfort and environmental impact.',
    },
    inputCard: {
      label: 'Tell us about your trip',
      placeholder: 'Tell us where you\'re going, who\'s traveling, and what you need…',
      defaultQuery: 'Mumbai to Goa with 2 children and 1 senior. I need a wheelchair, accessible transport and an accessible hotel.',
      buttonText: 'Find My Options',
      analyzingText: 'Analyzing trip details…',
      errorFallbackNotice: 'AI extraction is unavailable. We have opened the standard requirement form so you can configure your trip directly.',
      helperText: 'You can review and edit everything before we search.',
      charCount: 'chars',
      clear: 'Clear',
      voiceInputTooltip: 'Dictate in English, Hindi, or Marathi',
    },
    clarification: {
      heading: 'Trip Clarification',
      step: 'Question',
      of: 'of',
      foundPrefix: 'I found',
      andLabel: 'and',
      childrenLabel: 'children',
      seniorLabel: 'senior traveler(s)',
      adultsLabel: 'Adults traveling',
      answerPlaceholder: 'Enter number of adults…',
      continueBtn: 'Continue',
      skipBtn: 'Skip and fill in form',
    },
    examplePrompts: {
      heading: 'Try something like',
      items: [
        {
          id: 'prompt-1',
          label: 'Weekend trip from Mumbai to Goa under ₹20,000',
          query: 'Weekend trip from Mumbai to Goa under ₹20,000 with low carbon options',
        },
        {
          id: 'prompt-2',
          label: 'Traveling with my wheelchair-using parent',
          query: 'Traveling with my wheelchair-using parent from Delhi to Jaipur, step-free hotels and ramped transport',
        },
        {
          id: 'prompt-3',
          label: 'Low-carbon family trip with minimal walking',
          query: 'Low-carbon family trip from Bengaluru to Mysore with minimal walking and shaded accessible paths',
        },
        {
          id: 'prompt-4',
          label: 'Kerala backwaters with step-free boarding',
          query: 'Kochi to Alleppey for 3 seniors, battery-assisted transfers, step-free eco-resort',
        }
      ],
    },
    valueProps: {
      title: 'Built for conscious, comfortable journeys',
      items: [
        {
          symbol: '♿',
          title: 'Accessibility',
          description: 'Find options that match your specific accessibility needs — from step-free boarding to roll-in showers.',
          tag: 'Tailored comfort',
          badgeState: 'verified' ,
        },
        {
          symbol: '🌱',
          title: 'Lower-impact travel',
          description: 'Compare estimated emissions and lower-impact alternatives across rail, electric cabs, and eco-certified stays.',
          tag: '-60% average CO₂',
          badgeState: 'verified' ,
        },
        {
          symbol: '₹',
          title: 'Practical choices',
          description: 'Balance cost, time and convenience with transparent fare breakdowns and realistic transfer windows.',
          tag: 'No hidden trade-offs',
          badgeState: 'community-confirmed' ,
        },
        {
          symbol: '✓',
          title: 'Clear evidence',
          description: 'See what is verified, reported, community-confirmed or still unverified so you travel with confidence.',
          tag: 'Audited data',
          badgeState: 'verified' ,
        }
      ]
    },
    editorial: {
      kicker: 'The Decision Philosophy',
      heading: 'A better way to choose your journey.',
      supporting: 'We compare travel options across accessibility, cost, time, convenience and environmental impact — so you can understand the trade-offs before you choose.',
      manifesto: '“True luxury in modern India is knowing that every member of your family can move freely, without friction, while leaving the sacred landscapes we visit undisturbed.”',
      attribution: 'The Green & Inclusive Travel Charter',
      bullet1Title: 'Zero Assumptions on Mobility',
      bullet1Desc: 'We audit doorway widths, curb ramps, battery wheelchair charging points, and station porters across Indian routes.',
      bullet2Title: 'Carbon Transparency, Simplified',
      bullet2Desc: 'Calculated using real Indian grid and transit emissions factors, comparing high-speed electric trains like Vande Bharat against domestic flights.',
    },
    convergence: {
      kicker: 'Harmonious Design',
      title: 'Where accessibility and sustainability meet.',
      description: 'Often treated as separate priorities, universal accessibility and environmental mindfulness strengthen each other. Shared electric transit, step-free rail hubs, and low-waste architectural stays create more dignified journeys for all travelers.',
      leftLabel: 'Accessibility',
      leftDesc: 'Step-free transit · Sensory quiet spaces · Tactile wayfinding · Assistive baggage',
      rightLabel: 'Sustainability',
      rightDesc: 'Electrified rail corridors · Zero-single-use stays · Local farm dining · Minimal carbon footprint',
      centerLabel: 'YOUR JOURNEY',
      centerSub: 'Thoughtfully curated for India',
    },
    business: {
      heading: 'Make your property easier to discover.',
      supporting: 'Share your accessibility and sustainability practices, understand traveler demand, and discover opportunities to improve.',
      cta: 'For Businesses',
      tagline: 'Join 450+ verified eco-homestays, heritage villas, and transport operators across India.',
      cardTitle: 'Host & Operator Registry',
      bullet1: 'Free accessibility and carbon baseline audit guide',
      bullet2: 'Direct visibility to travelers with specific physical & dietary requirements',
      button: 'Partner with Us',
    },
    reviewModal: {
      title: 'Review Your Trip Setup',
      subtitle: 'The engine extracted these parameters from your prompt. Review and adjust anything before discovering options.',
      routeLabel: 'Route',
      travelersLabel: 'Travel Party',
      accessLabel: 'Accessibility Requirements',
      sustainabilityLabel: 'Sustainability Preferences',
      confirmAction: 'Continue with these Preferences',
      toastMessage: 'Setup saved. You are ready to proceed with these verified parameters.',
    },
    footer: {
      brand: 'Green & Inclusive Travel',
      description: 'A personalized travel decision engine dedicated to low-carbon, universally accessible journeys across India.',
      planTrip: 'Plan a Trip',
      explore: 'Explore',
      forBusinesses: 'For Businesses',
      about: 'About',
      copyright: '© 2026 Green & Inclusive Travel Inc. Designed for sustainable and accessible travel in India.',
    },
    bottomNav: {
      search: 'Search',
      explore: 'Explore',
      trips: 'Trips',
      profile: 'Profile',
    }
  },
  hi: {
    brandName: 'Green & Inclusive Travel',
    tagline: 'भारत में सतत और सुलभ यात्रा के लिए व्यक्तिगत निर्णय इंजन',
    nav: {
      planTrip: 'यात्रा योजना',
      explore: 'खोजें',
      trips: 'मेरी यात्राएं',
      forBusinesses: 'व्यवसायों के लिए',
      signIn: 'साइन इन करें',
      profile: 'प्रोफ़ाइल',
      language: 'भाषा',
    },
    hero: {
      headlinePart1: 'सार्थक यात्रा।',
      headlinePart2: 'सुलभ यात्रा।',
      headlinePart3: 'पर्यावरण-हितैषी यात्रा।',
      supporting: 'अपनी प्राथमिकताओं के अनुसार यात्रा की योजना बनाएं — सुगमता, बजट, समय, आराम और पर्यावरण पर प्रभाव।',
    },
    inputCard: {
      label: 'अपनी यात्रा के बारे में हमें बताएं',
      placeholder: 'बताएं कि आप कहां जा रहे हैं, कौन साथ है, और आपको क्या आवश्यकताएं हैं…',
      defaultQuery: 'मुंबई से गोवा 2 बच्चों और 1 वरिष्ठ नागरिक के साथ। मुझे व्हीलचेयर, सुलभ वाहन और सुलभ होटल की आवश्यकता है।',
      buttonText: 'मेरे विकल्प खोजें',
      analyzingText: 'विवरण विश्लेषित हो रहा है…',
      errorFallbackNotice: 'एआई निष्कर्षण सेवा उपलब्ध नहीं है। हमने आपके लिए मानक आवश्यकता फ़ॉर्म खोल दिया है।',
      helperText: 'खोज शुरू करने से पहले आप सब कुछ जांच और संपादित कर सकते हैं।',
      charCount: 'अक्षर',
      clear: 'साफ़ करें',
      voiceInputTooltip: 'हिंदी या अंग्रेजी में बोलें',
    },
    clarification: {
      heading: 'यात्रा स्पष्टीकरण',
      step: 'प्रश्न',
      of: 'कुल',
      foundPrefix: 'मुझे मिला:',
      andLabel: 'और',
      childrenLabel: 'बच्चे',
      seniorLabel: 'वरिष्ठ नागरिक',
      adultsLabel: 'वयस्क यात्री',
      answerPlaceholder: 'वयस्कों की संख्या दर्ज करें…',
      continueBtn: 'आगे बढ़ें',
      skipBtn: 'छोड़ें और फ़ॉर्म में भरें',
    },
    examplePrompts: {
      heading: 'इस प्रकार प्रयास करें',
      items: [
        {
          id: 'prompt-1',
          label: 'मुंबई से गोवा सप्ताहांत यात्रा ₹20,000 के भीतर',
          query: 'मुंबई से गोवा कम कार्बन उत्सर्जन वाली सप्ताहांत यात्रा ₹20,000 के बजट में',
        },
        {
          id: 'prompt-2',
          label: 'व्हीलचेयर का उपयोग करने वाले माता-पिता के साथ यात्रा',
          query: 'दिल्ली से जयपुर व्हीलचेयर-सुलभ होटल और रैंप वाले इलेक्ट्रिक परिवहन के साथ यात्रा',
        },
        {
          id: 'prompt-3',
          label: 'न्यूनतम पैदल चलने वाली कम-कार्बन पारिवारिक यात्रा',
          query: 'बेंगलुरु से मैसूर परिवार के साथ न्यूनतम पैदल चलने और सुलभ रास्तों वाली यात्रा',
        },
        {
          id: 'prompt-4',
          label: 'केरल बैकवाटर्स में सीढ़ी-मुक्त नौकायन',
          query: 'कोच्चि से अल्लेप्पी 3 वरिष्ठ नागरिकों के लिए, सहायता प्राप्त सुलभ पर्यावरण-अनुकूल आवास',
        }
      ],
    },
    valueProps: {
      title: 'सार्थक और आरामदायक यात्राओं के लिए निर्मित',
      items: [
        {
          symbol: '♿',
          title: 'सुगमता (Accessibility)',
          description: 'ऐसी यात्रा विकल्प खोजें जो आपकी शारीरिक आवश्यकताओं के अनुरूप हों — सीढ़ी-मुक्त स्टेशन से रोल-इन शॉवर तक।',
          tag: 'अनुकूलित आराम',
          badgeState: 'verified' ,
        },
        {
          symbol: '🌱',
          title: 'कम-प्रभाव वाली यात्रा',
          description: 'ट्रेन, इलेक्ट्रिक कैब और प्रमाणित ईको-स्टे में अनुमानित कार्बन उत्सर्जन की तुलना करें।',
          tag: '-60% कार्बन कमी',
          badgeState: 'verified' ,
        },
        {
          symbol: '₹',
          title: 'व्यावहारिक विकल्प',
          description: 'स्पष्ट किराए और वास्तविक समय के साथ लागत, समय और सुविधा में संतुलन बनाएं।',
          tag: 'पारदर्शी मूल्य',
          badgeState: 'community-confirmed' ,
        },
        {
          symbol: '✓',
          title: 'प्रमाणित साक्ष्य',
          description: 'देखें कि क्या सत्यापित है, समुदाय द्वारा पुष्ट है, ताकि आप पूरे विश्वास के साथ यात्रा करें।',
          tag: 'सत्यापित विवरण',
          badgeState: 'verified' ,
        }
      ]
    },
    editorial: {
      kicker: 'यात्रा दर्शन',
      heading: 'अपनी यात्रा चुनने का एक बेहतर तरीका।',
      supporting: 'हम सुगमता, लागत, समय, सुविधा और पर्यावरणीय प्रभाव के आधार पर विकल्पों की तुलना करते हैं — ताकि आप चयन करने से पहले सभी पहलुओं को समझ सकें।',
      manifesto: '“सच्ची विलासिता यह है कि परिवार का प्रत्येक सदस्य बिना किसी रुकावट के स्वतंत्र रूप से घूम सके, और हमारी प्रकृति पर कोई खरोंच न आए।”',
      attribution: 'ग्रीन एंड इनक्लूसिव ट्रैवल घोषणापत्र',
      bullet1Title: 'सुगमता पर पूर्ण ध्यान',
      bullet1Desc: 'हम भारतीय मार्गों पर दरवाजों की चौड़ाई, रैंप, बैटरी व्हीलचेयर चार्जिंग और कुली सहायता का सत्यापन करते हैं।',
      bullet2Title: 'सच्ची कार्बन पारदर्शिता',
      bullet2Desc: 'वंदे भारत जैसी इलेक्ट्रिक ट्रेनों और उड़ानों के वास्तविक उत्सर्जन कारकों की तुलना।',
    },
    convergence: {
      kicker: 'समन्वित दृष्टिकोण',
      title: 'जहां सुगमता और स्थिरता एक साथ आती हैं।',
      description: 'सुलभ बुनियादी ढांचा और पर्यावरण-संवेदनशीलता एक दूसरे को मजबूत करते हैं। साझा इलेक्ट्रिक परिवहन, सीढ़ी-मुक्त हब और न्यूनतम-अपशिष्ट आवास सभी के लिए गरिमापूर्ण यात्रा बनाते हैं।',
      leftLabel: 'सुगमता (Accessibility)',
      leftDesc: 'सीढ़ी-मुक्त पारगमन · शांत संवेदी क्षेत्र · स्पर्शनीय संकेत · सहायता प्राप्त बैगेज',
      rightLabel: 'स्थिरता (Sustainability)',
      rightDesc: 'विद्युतीकृत रेल गलियारे · प्लास्टिक-मुक्त स्टे · स्थानीय जैविक भोजन · न्यूनतम कार्बन',
      centerLabel: 'आपकी यात्रा',
      centerSub: 'भारत के लिए विचारपूर्वक डिज़ाइन की गई',
    },
    business: {
      heading: 'अपनी संपत्ति को अधिक यात्रियों तक पहुंचाएं।',
      supporting: 'अपनी सुलभता और पर्यावरण अनुकूल प्रथाओं को साझा करें, यात्रियों की मांग समझें और सुधार के अवसर खोजें।',
      cta: 'व्यवसायों के लिए',
      tagline: 'भारत भर के 450+ सत्यापित ईको-होमस्टे और ऑपरेटरों से जुड़ें।',
      cardTitle: 'हॉस्पिटैलिटी पार्टनर पोर्टल',
      bullet1: 'निःशुल्क सुगमता और कार्बन ऑडिट गाइड',
      bullet2: 'विशिष्ट आवश्यकताओं वाले यात्रियों के लिए सीधी दृश्यता',
      button: 'हमारे भागीदार बनें',
    },
    reviewModal: {
      title: 'अपनी यात्रा सेटअप की समीक्षा करें',
      subtitle: 'इंजन ने आपके विवरण से इन आवश्यकताओं की पहचान की है। विकल्प देखने से पहले कुछ भी संपादित कर सकते हैं।',
      routeLabel: 'मार्ग',
      travelersLabel: 'यात्री समूह',
      accessLabel: 'सुगमता आवश्यकताएं',
      sustainabilityLabel: 'पर्यावरणीय प्राथमिकताएं',
      confirmAction: 'इन प्राथमिकताओं के साथ आगे बढ़ें',
      toastMessage: 'सेटअप सुरक्षित हो गया। आप विकल्प देखने के लिए तैयार हैं।',
    },
    footer: {
      brand: 'Green & Inclusive Travel',
      description: 'भारत भर में कम कार्बन और सार्वभौमिक रूप से सुलभ यात्राओं के लिए समर्पित व्यक्तिगत निर्णय इंजन।',
      planTrip: 'यात्रा योजना',
      explore: 'खोजें',
      forBusinesses: 'व्यवसायों के लिए',
      about: 'हमारे बारे में',
      copyright: '© 2026 Green & Inclusive Travel Inc. भारत में सतत एवं सुलभ यात्रा के लिए।',
    },
    bottomNav: {
      search: 'खोजें',
      explore: 'एक्सप्लोर',
      trips: 'यात्राएं',
      profile: 'प्रोफ़ाइल',
    }
  },
  mr: {
    brandName: 'Green & Inclusive Travel',
    tagline: 'भारतातील शाश्वत आणि सुलभ प्रवासासाठी वैयक्तिक प्रवास निर्णय इंजिन',
    nav: {
      planTrip: 'प्रवास नियोजन',
      explore: 'शोधा',
      trips: 'माझे प्रवास',
      forBusinesses: 'व्यवसायांसाठी',
      signIn: 'साइन इन',
      profile: 'प्रोफाइल',
      language: 'भाषा',
    },
    hero: {
      headlinePart1: 'शाश्वत प्रवास.',
      headlinePart2: 'हलका प्रवास.',
      headlinePart3: 'सर्वांसाठी सर्वसमावेशक.',
      supporting: 'तुमच्या महत्त्वाच्या घटकांनुसार प्रवासाचे नियोजन करा — सुलभता, बजेट, वेळ, आराम आणि पर्यावरणावरील प्रभाव.',
    },
    inputCard: {
      label: 'तुमच्या प्रवासाबद्दल आम्हाला सांगा',
      placeholder: 'तुम्ही कुठे जात आहात, कोण प्रवास करत आहे आणि तुम्हाला काय हवे आहे ते सांगा…',
      defaultQuery: 'मुंबई ते गोवा २ लहान मुले आणि १ ज्येष्ठ नागरिकांसह. मला व्हीलचेअर, सुलभ वाहतूक आणि सुलभ हॉटेल हवे आहे.',
      buttonText: 'माझे पर्याय शोधा',
      analyzingText: 'तपशील तपासत आहे…',
      errorFallbackNotice: 'एआय सेवा सध्या अनुपलब्ध आहे. आम्ही थेट मानक आवश्यकता फॉर्म उघडला आहे.',
      helperText: 'शोध सुरू करण्यापूर्वी तुम्ही सर्व काही तपासू आणि संपादित करू शकता.',
      charCount: 'अक्षरे',
      clear: 'पुसा',
      voiceInputTooltip: 'मराठी किंवा इंग्रजीत बोला',
    },
    clarification: {
      heading: 'प्रवास स्पष्टीकरण',
      step: 'प्रश्न',
      of: 'पैकी',
      foundPrefix: 'नोंद आढळली:',
      andLabel: 'आणि',
      childrenLabel: 'मुलं',
      seniorLabel: 'ज्येष्ठ नागरिक',
      adultsLabel: 'प्रौढ प्रवासी',
      answerPlaceholder: 'प्रौढ प्रवाशांची संख्या नोंदवा…',
      continueBtn: 'पुढे जा',
      skipBtn: 'वगळा आणि फॉर्म भरा',
    },
    examplePrompts: {
      heading: 'असे काहीतरी वापरून पहा',
      items: [
        {
          id: 'prompt-1',
          label: 'मुंबई ते गोवा वीकेंड ट्रिप ₹२०,००० च्या आत',
          query: 'मुंबई ते गोवा कमी कार्बन उत्सर्जनासह वीकेंड ट्रिप ₹२०,००० बजेटमध्ये',
        },
        {
          id: 'prompt-2',
          label: 'व्हीलचेअर वापरणाऱ्या पालकांसह प्रवास',
          query: 'पालकांसह व्हीलचेअर-सुलभ आणि पायऱ्या नसलेल्या प्रवासाची सोय',
        },
        {
          id: 'prompt-3',
          label: 'कमी चालणे लागणारा कमी-कार्बन कौटुंबिक प्रवास',
          query: 'कुटुंबासह कमी चालणे आणि सुलभ मार्ग असलेला पर्यावरणपूरक प्रवास',
        },
        {
          id: 'prompt-4',
          label: 'कोकण रेल्वेतून निसर्गरम्य आणि सुलभ प्रवास',
          query: 'मुंबई ते सावंतवाडी पायऱ्या नसलेले बोर्डिंग आणि इको-स्टे',
        }
      ],
    },
    valueProps: {
      title: 'जाणीवपूर्वक आणि आरामदायी प्रवासासाठी निर्मित',
      items: [
        {
          symbol: '♿',
          title: 'सुलभता (Accessibility)',
          description: 'तुमच्या नेमक्या शारीरिक गरजांनुसार पर्याय शोधा — पायऱ्यांविना बोर्डिंगपासून ते रोल-इन शॉवर्सपर्यंत.',
          tag: 'अनुकूल आराम',
          badgeState: 'verified' ,
        },
        {
          symbol: '🌱',
          title: 'कमी प्रभावाचा प्रवास',
          description: 'रेल्वे, इलेक्ट्रिक वाहने आणि प्रमाणित इको-स्टेच्या कार्बन उत्सर्जनाची पारदर्शक तुलना करा.',
          tag: '-६०% कार्बन बचत',
          badgeState: 'verified' ,
        },
        {
          symbol: '₹',
          title: 'व्यावहारिक निवड',
          description: 'खर्च, वेळ आणि सोय यात समतोल साधा आणि योग्य निर्णय घ्या.',
          tag: 'पारदर्शक दर',
          badgeState: 'community-confirmed' ,
        },
        {
          symbol: '✓',
          title: 'स्पष्ट पुरावा',
          description: 'काय पडताळलेले आहे, काय नोंदवले आहे ते स्पष्टपणे पहा जेणेकरून आत्मविश्वासाने प्रवास करता येईल.',
          tag: 'सत्यापित माहिती',
          badgeState: 'verified' ,
        }
      ]
    },
    editorial: {
      kicker: 'प्रवासाचा दृष्टिकोन',
      heading: 'तुमचा प्रवास निवडण्याचा एक उत्तम मार्ग.',
      supporting: 'आम्ही सुलभता, खर्च, वेळ, सोय आणि पर्यावरणीय प्रभाव या सर्वांची तुलना करतो — जेणेकरून तुम्ही विचारपूर्वक निवड करू शकाल.',
      manifesto: '“खरा प्रवास तोच असतो जिथे कुटुंबातील प्रत्येक व्यक्ती सहजतेने फिरू शकते आणि निसर्गावर कोणतीही हानी पोहोचत नाही.”',
      attribution: 'ग्रीन अँड इन्क्लुझिव्ह ट्रॅव्हल संकल्प',
      bullet1Title: 'हालचालीवर पूर्ण विचार',
      bullet1Desc: 'आम्ही भारतीय मार्गांवरील दारांची रुंदी, रॅम्प, व्हीलचेअर चार्जिंग आणि मदतनीस व्यवस्था तपासतो.',
      bullet2Title: 'कार्बन पारदर्शकता',
      bullet2Desc: 'वंदे भारतसारख्या इलेक्ट्रिक ट्रेन्स आणि विमानांच्या उत्सर्जनाची थेट तुलना.',
    },
    convergence: {
      kicker: 'सुसंगत समन्वय',
      title: 'जिथे सुलभता आणि पर्यावरण-स्नेह एकत्र येतात.',
      description: 'सुलभता आणि पर्यावरण रक्षण एकमेकांना पूरक आहेत. सामूहिक इलेक्ट्रिक वाहतूक, पायऱ्यांविना रेल्वे हब आणि इको-स्टे सर्वांसाठी सन्मानजनक प्रवास घडवतात.',
      leftLabel: 'सुलभता (Accessibility)',
      leftDesc: 'पायऱ्या नसलेला प्रवास · शांत संवेदी जागा · सुलभ मार्गदर्शक खुणा',
      rightLabel: 'शाश्वतता (Sustainability)',
      rightDesc: 'विद्युतीकृत रेल्वे मार्ग · प्लास्टिक-मुक्त वास्तव्य · स्थानिक अन्न · कमी कार्बन',
      centerLabel: 'तुमचा प्रवास',
      centerSub: 'भारतासाठी जाणीवपूर्वक रचलेला',
    },
    business: {
      heading: 'तुमचे हॉटेल व रिसॉर्ट पर्यटकांपर्यंत पोहोचवा.',
      supporting: 'तुमच्या सुलभता आणि पर्यावरणपूरक सेवांची नोंद करा, पर्यटकांच्या गरजा समजून घ्या आणि सुधारणा करा.',
      cta: 'व्यवसायांसाठी',
      tagline: 'भारतभरातील ४५०+ प्रमाणित इको-स्टे आणि ऑपरेटर्समध्ये सहभागी व्हा.',
      cardTitle: 'हॉस्पिटॅलिटी पार्टनर नोंदणी',
      bullet1: 'मोफत सुलभता आणि कार्बन ऑडिट मार्गदर्शक',
      bullet2: 'विशेष गरजा असलेल्या प्रवाशांपर्यंत थेट पोहोच',
      button: 'भागीदार व्हा',
    },
    reviewModal: {
      title: 'प्रवास रचनेची पाहणी करा',
      subtitle: 'तुमच्या वाक्यावरून इंजिनने या घटकांची नोंद घेतली आहे. शोधण्यापूर्वी बदल करू शकता.',
      routeLabel: 'मार्ग',
      travelersLabel: 'प्रवासी संख्या',
      accessLabel: 'सुलभता गरजा',
      sustainabilityLabel: 'पर्यावरण प्राधान्ये',
      confirmAction: 'या प्राधान्यांसह पुढे जा',
      toastMessage: 'माहिती सुरक्षित झाली. तुम्ही पर्याय पाहण्यासाठी तयार आहात.',
    },
    footer: {
      brand: 'Green & Inclusive Travel',
      description: 'कमी कार्बन आणि सर्वांसाठी सुलभ प्रवासासाठी भारतातील वैयक्तिक प्रवास निर्णय इंजिन.',
      planTrip: 'प्रवास नियोजन',
      explore: 'शोधा',
      forBusinesses: 'व्यवसायांसाठी',
      about: 'आमच्याबद्दल',
      copyright: '© २०२६ Green & Inclusive Travel Inc. शाश्वत आणि सुलभ प्रवासासाठी.',
    },
    bottomNav: {
      search: 'शोधा',
      explore: 'एक्सप्लोर',
      trips: 'प्रवास',
      profile: 'प्रोफाइल',
    }
  }
};
import fs from 'fs';
for (const lang of ['en', 'hi', 'mr']) {
    const path = `src/i18n/${lang}/b2c.json`;
    const dict = JSON.parse(fs.readFileSync(path, 'utf8'));
    dict['home'] = translations[lang];
    fs.writeFileSync(path, JSON.stringify(dict, null, 2), 'utf8');
}
