const t = {
    en: {
      title: 'Trip Requirements',
      subtitle: 'Review and refine your travel parameters. All fields remain fully editable.',
      back: 'Back to Search',
      routeHeading: 'Route & Destinations',
      originLabel: 'Origin City',
      originPlaceholder: 'e.g. Mumbai',
      destLabel: 'Destination City',
      destPlaceholder: 'e.g. Goa',
      travelersHeading: 'Travel Party',
      adults: 'Adults (12+ yrs)',
      children: 'Children (2–11 yrs)',
      seniors: 'Seniors (60+ yrs)',
      wheelchair: 'Wheelchair Users',
      nightsLabel: 'Nights (Duration)',
      nightsHelper: 'Number of nights staying',
      accessibilityHeading: 'Accessibility Requirements',
      generalFlagsNotice: 'General accessibility flags extracted from your prompt:',
      chipsHelper: 'Select any specific barrier-free features required for your journey:',
      budgetHeading: 'Budget Limit (Max per person / room)',
      submitBtn: 'Discover Travel Options',
      submittedMsg: 'Requirements saved! Ready for recommendation engine search.',
      unverifiedToggle: 'Include unverified or self-reported data states',
    },
    hi: {
      title: 'यात्रा आवश्यकताएं',
      subtitle: 'अपनी प्राथमिकताओं की समीक्षा करें और आवश्यकतानुसार बदलाव करें। सभी फ़ील्ड संपादन योग्य हैं।',
      back: 'वापस खोज पर जाएं',
      routeHeading: 'मार्ग और गंतव्य',
      originLabel: 'प्रस्थान शहर',
      originPlaceholder: 'उदा. मुंबई',
      destLabel: 'गंतव्य शहर',
      destPlaceholder: 'उदा. गोवा',
      travelersHeading: 'यात्री समूह',
      adults: 'वयस्क (१२+ वर्ष)',
      children: 'बच्चे (२–११ वर्ष)',
      seniors: 'वरिष्ठ नागरिक (६०+ वर्ष)',
      wheelchair: 'व्हीलचेयर उपयोगकर्ता',
      nightsLabel: 'रातें (अवधि)',
      nightsHelper: 'रुकने की रातों की संख्या',
      accessibilityHeading: 'सुलभता आवश्यकताएं',
      generalFlagsNotice: 'आपके विवरण से पहचानी गई सामान्य सुलभता प्राथमिकताएं:',
      chipsHelper: 'अपनी यात्रा के लिए आवश्यक विशिष्ट सुविधाएं चुनें:',
      budgetHeading: 'अधिकतम बजट सीमा',
      submitBtn: 'यात्रा विकल्प खोजें',
      submittedMsg: 'आवश्यकताएं सहेजी गईं!',
      unverifiedToggle: 'अपुष्ट या स्व-रिपोर्ट किए गए विकल्प भी शामिल करें',
    },
    mr: {
      title: 'प्रवास आवश्यकता',
      subtitle: 'आपल्या प्रवास घटकांची तपासणी करा. सर्व माहिती संपादन करण्याजोगी आहे.',
      back: 'मागे शोधावर जा',
      routeHeading: 'मार्ग आणि ठिकाण',
      originLabel: 'प्रस्थान शहर',
      originPlaceholder: 'उदा. मुंबई',
      destLabel: 'गंतव्य शहर',
      destPlaceholder: 'उदा. गोवा',
      travelersHeading: 'प्रवासी संख्या',
      adults: 'प्रौढ (१२+ वर्षे)',
      children: 'लहान मुले (२–११ वर्षे)',
      seniors: 'ज्येष्ठ नागरिक (६०+ वर्षे)',
      wheelchair: 'व्हीलचेअर वापरकर्ते',
      nightsLabel: 'रात्री (कालावधी)',
      nightsHelper: 'मुक्कामाच्या रात्रींची संख्या',
      accessibilityHeading: 'सुलभता गरजा',
      generalFlagsNotice: 'तुमच्या वर्णनातून नोंदवलेली सामान्य सुलभता:',
      chipsHelper: 'प्रवासासाठी आवश्यक असणाऱ्या विशिष्ट सुविधा निवडा:',
      budgetHeading: 'कमाल बजेट मर्यादा',
      submitBtn: 'प्रवास पर्याय शोधा',
      submittedMsg: 'आवश्यकता नोंदवली गेली!',
      unverifiedToggle: 'अपुष्ट किंवा स्वयं-नोंदवलेले पर्याय समाविष्ट करा',
    },
  }
import fs from 'fs';
for (const lang of ['en', 'hi', 'mr']) {
    const path = `src/i18n/${lang}/b2c.json`;
    const dict = JSON.parse(fs.readFileSync(path, 'utf8'));
    dict['reqForm'] = t[lang];
    fs.writeFileSync(path, JSON.stringify(dict, null, 2), 'utf8');
}
